### ISSUE TITLE
Produire une synthèse sur les solutions de chaînes éditoriales

### ISSUE THREAD

**Issue by emchateau** [ouvroir/encyclopedie#6]
Discuter des avantages/inconvénients de la pile technologique XML vs HTML5/JSON
Contrôle des données et consistance
Automatisations
Architecture et flux de travail
Enjeux de pérennisation

cf. https://github.com/ouvroir/encyclopedie/blob/main/chaines.md

**Comment by lenaMK** [comment]
fait par roch et antoine?

**Comment by emchateau** [comment]
Oui en partie. Après la synthèse il faudra décider ce que l’on fait.
