### ISSUE TITLE
Lister des éditeurs web pour la publication d’articles scientifiques

### ISSUE THREAD

**Issue by emchateau** [ouvroir/encyclopedie#7]
Depuis quelques années de nombreux éditeurs web spécialisés ont été développés pour la publication savante. Faire un état des lieux avec une attention particulière sur les dépendances, la prise en charge de fonctionnalités dédiées pour les textes savants (notes, biblio, légendes).
- Présentation
- Architecture
- Technologie
- Interopérabilité
- Licences
- Avantages
- Inconvénients

Classer les éditeurs selon les domaines d’application
- génériques (CMS, web)
- académiques (fonctionnalités spécifiques pour l’édition scientifique : note, etc.)
- XML

Critères
- gestion des notes de bas de page
- gestion bibliographique
- exposants et orthotypographie
- mode révision
- multi-author
- commentaires
- customisability

cf. https://github.com/ouvroir/encyclopedie/blob/main/editeurs.md fichier avec liens de départ

**Comment by emchateau** [comment]
Demander liste à @emchateau

**Comment by emchateau** [comment]
- prose.io
- substance, etc.

**Comment by lenaMK** [comment]
fait par Roch et Antoine?

**Comment by emchateau** [comment]
Cela va nous apporter des éléments mais à mon avis très partiels. Il restera à compléter l’état de l’art en fonction de l’orientation que l’on aura choisie.
